FROM debian:latest

# Base
RUN apt-get update
RUN apt-get upgrade

# python and flask
RUN apt-get -y install python3 python3-flask

# get vuln app in
RUN mkdir /opt/app
RUN mkdir /opt/app/templates
RUN mkdir /opt/app/files/
COPY ./app.py /opt/app/
ADD ./templates/ /opt/app/templates/

# run our bad app on default 5000
CMD ["/usr/bin/python3", "/opt/app/app.py"]